spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  servlet:
    multipart:
      max-file-size: 10MB
  main:
    allow-circular-references: true

hoxify:
  upload-path: pictures
---
spring:
  config:
    activate:
      on-profile: production
hoxify:
  upload-path: storage-production
---
spring:
  config:
    activate:
      on-profile: dev
hoxify:
  upload-path: storage-dev